### ISSUE TITLE
Font size Screencast Key -VS- Render 1.0.0

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#135] opened 2022-11-01 16:55 UTC
<img width="392" alt="image" src="https://user-images.githubusercontent.com/4253305/199287559-baf4a7ae-3f46-4d68-8d40-285800cecce4.png">
Blender 3.3.2 and 3.4.0

ScreenCast Key 3.8

### Expected behavior

I found out and I notice oh really about Blender 3.4 Alpha too big font size than Blender 3.3.2

See Youtube.
I will send report a Ticket on Blender too.

https://youtu.be/1kocc-7bOsw

Blender Report a Ticket: https://developer.blender.org/T102213

**Comment by nutti** [comment] 2022-11-02 07:14
From my environment, the size is no difference among these versions.
Below image shows the display with `font size = 100`

![github-20221102](https://user-images.githubusercontent.com/1463952/199423472-f0ae3618-2021-4b6c-ad27-80767d04d979.png)

I think this seems the environmental issue.

**Comment by nutti** [comment] 2022-11-02 09:08
I can not help your issue because I could not prepare your environment.
It is difficult for us to support the specific environment.

BTW, is it a critical problem?
We can change font size from Sidebar, so you can adjust the font size easily.
Perhaps, the configuration is not inherits between Blender versions?

**Comment by mac4kent** [comment] 2022-11-02 09:14
What is critical, configuration, inherits?
yes any version problem because of F12 render on top font text size try avoid.
Also 3.4.0 problem too.

**Comment by nutti** [comment] 2022-11-02 09:19
Ah, I understood this issue.
The main problem is Blender does not return to the original font size before rendering the text on render result.
I think this should be reported to the Blender itself because the other add-on will effect this issue too.

**Comment by mac4kent** [comment] 2022-11-02 09:24
Sureeeeeeee

**Comment by mac4kent** [comment] 2022-11-09 03:44
Hello Nutti, Did you try follow my picture preferences above yet?
Interface and Theme?

**Comment by nutti** [comment] 2022-11-09 06:25
I have already cleared the cause of this issue.
I posted the question at [D.B.O](https://developer.blender.org/T102213#1441342), but there is no reply.

**Comment by mac4kent** [comment] 2022-11-09 11:13
Allright

**Comment by nutti** [comment] 2022-12-14 07:19
The patch is now merged to the official repos.
https://developer.blender.org/rBb848de754621ccbf2e2960919699df796413f2c7

**Closed by nutti** 2022-12-14 07:19 UTC
Labels: bug, blender patch

**Comment by mac4kent** [comment] 2022-12-16 01:58
There is not resolve I got download USA December 15, 2022 and Europe is December 16, 2022 and I did got download today. See picture https://imgur.com/Ky9i4Wu

**Comment by nutti** [comment] 2022-12-16 10:12
Seems fixed from the comment of D.B.O now.

**Comment by mac4kent** [comment] 2022-12-16 10:48
Yes. Blender 3.5.0 did fixed but 3.4.1 did not fix. I will wait for next resolve 3.4.1

**Comment by mac4kent** [comment] 2022-12-18 16:11
They did resolve Blender 3.4.1 finally. Now I able to see render text on top on Blender 3.4.1 and 3.5.0
