### ISSUE TITLE
the addon makes blender's autosave feature not working

### ISSUE THREAD

**Issue by fexa6** [nutti/Screencast-Keys#193] opened 2024-01-17 13:42 UTC
### System Information
  
* OS: Windows
* Blender version: 4.0.2
* Add-on version: 3.12

### Expected behavior

Everything work as usual

### Description about the bug**

I found my Blender autosave is not working since few days ago. I wasnt sure about why.(pretty sure all preference setings are fine). so i deleted everything about blender ,and reinstalled it. everything is back to normal. so i tried to find our if any Addon caused this problem,then i found out it happens once i activate Screencastkeys.

### Screenshots/Files [Optional]  

the consel reports when i try to find autosave files.:
Cannot read file "C:\Users\Fexa\AppData\Local\Temp\try01_14376_autosave.blend": No such file or directory
try01 is the file i used for testing.

### Additional comments [Optional]
I'll do more tests, the only way to fix this is reinstall blender and not use this addon...strange.

**Comment by nutti** [comment] 2024-01-18 09:25
@fexa6 

Autosave feature is an experiment feature.
So, you may face with unexpected behavior.

Could you share the .blend file if possible?
Reproducing this error is difficult for us.

**Comment by nutti** [comment] 2024-02-03 10:46
@fexa6 

Any update?

**Comment by nutti** [comment] 2024-02-14 11:22
Close this issue because of no reaction.
Please let me if this issue is still valid.

**Closed by nutti** 2024-02-14 11:22 UTC
Labels: invalid
