### ISSUE TITLE
Blender always have not responding when first time open

### ISSUE THREAD

**Issue by nhok0169** [nutti/Screencast-Keys#137] opened 2022-11-18 10:43 UTC
### System Information
  
* OS: win10
* Blender version: 3.2.2
* Add-on version: 3.8
*
### Description about the bug**

when open blender first time on computer after turn it on it always not responding and i need close it and open it again. This error because im turn of function "enable on startup" when i turn it off i dont have that error.

**Comment by nutti** [comment] 2022-11-18 13:27
@nhok0169 

I could not reproduce your error.

> it always not responding

Could you explain this more detail?
Is there any error message if you open system console?

> This error because im turn off function "enable on startup"

It seems this behavior is correct.
When "enable on startup" is turned offf, Screencast Keys will not be enabled.

**Comment by nhok0169** [comment] 2022-11-19 02:02
@nutti like what i said everytime im open/restart my computer and open blender on my first time ( the eneble on startup check)
it make my blender not responding
i need turn it off with task manager and open again
but weird when the second time open it work
so im try turn of " enable on startup" and open/restart my pc and i dont have error about not responding when first time open it

**Comment by nutti** [comment] 2022-11-19 05:44
@nhok0169 

How about **system console**? Is there any output logs?
We could not investigate your issue any more if there is no clue.
Your procedure does not reproduce the issue on my environment.

**Comment by nhok0169** [comment] 2022-11-19 11:15
how i can get the log when it not responding bro 
i dont have anylog about that :(

**Comment by nutti** [comment] 2022-11-19 12:00
@nhok0169 

Is it possible to launch Blender from console (command prompt)?
You can see the instruction from [blender official site](https://docs.blender.org/manual/en/latest/advanced/command_line/launch/windows.html).
If you launch Blender from console, you can see the output log.

**Comment by nhok0169** [comment] 2022-11-19 15:15
@nutti here you go first picture it when i have not responding
![image](https://user-images.githubusercontent.com/49529571/202857733-6b573fa9-bcf1-4ccf-bc12-21fb887f76ef.png)
and here it normal after
![image](https://user-images.githubusercontent.com/49529571/202857764-f0048837-09b2-4695-b0cd-dcd0e5e96766.png)

**Comment by nutti** [comment] 2022-11-21 00:59
@nhok0169 

It seems no evidence from your log.
Is this issue still appear if you disable all other add-ons except for Screencast Keys?

Please send us .blend file if above issue is still occur.

**Comment by nhok0169** [comment] 2022-11-22 04:43
hmm im turn every addon off and turn on again and now i can open blender on the first open 
but some project can open without blend and some of them need open on blender cant open it normal when click blend file
so may be it not your plugin problem or your plugin have conflict with some plugin on my pc 
because before used your plugin it stil normal no error
here it the list 
![image](https://user-images.githubusercontent.com/49529571/203223478-c4fc332a-d17c-42cd-a655-c59ba64659d9.png)

**Comment by nutti** [comment] 2022-11-23 09:22
@nhok0169 

Thanks.
I tried your .blend file, and it works correctly on my environment.
I think this is the issue caused by the other add-ons.
Could you turn on/off your add-ons and check which add-on cause this issue?

**Comment by nhok0169** [comment] 2022-11-24 10:44
I have good news
every time i disable your plugin and turn it back on the error goes away for a few days and it comes back so i will check your cause when i get the error again
here are my settings
it's the same every time i have the problem
i will try updating my blender to the latest version
and I'll let you know if I get the error again
![image](https://user-images.githubusercontent.com/49529571/203764071-40ae51c5-a994-4c9c-b64b-8d392435c9aa.png)

**Comment by nutti** [comment] 2022-11-25 11:35
I will close this issue for now because this issue seems the Screencast Keys' issue.

**Closed by nutti** 2022-11-25 11:35 UTC
Labels: invalid

**Comment by nhok0169** [comment] 2022-11-27 06:35
hello im back
the error comback on 2 3 day after reset and now i found a combo have a error when turn on it same time with "enable on startup"
![final error with enebale on startup](https://user-images.githubusercontent.com/49529571/204119778-2e46c4b6-1a30-48da-afbc-85c20cd5a3d3.png)
cat blender 0.19 [https://github.com/absolute-quantum/cats-blender-plugin](url)
material combine [https://github.com/Grim-es/material-combiner-addon/releases/tag/2.1.2.4](url)
here it full video test error :
https://youtu.be/NKg3Ix72r-c

**Comment by nutti** [comment] 2022-11-27 10:31
@nhok0169 

I can reproduce the error with your .blend file when I enable the add-on "Cats Blender Plugin".
But I still could not reproduce the error with other .blend file.
It seems that this is the environmental issue or corner case, so please turn off "Enable On Startup" when this error is caused.

@CheeryLee 

Sorry to mention you for the old topic (#62).
Blender is stuck when we launch the Blender with enabling the option "Enable On Startup" on the specific case.
It seems that this stuck is caused by calling the operator from the registered draw callback.
Did you encounter this case on your environment?

**Comment by CheeryLee** [comment] 2022-11-30 17:38
@nutti 

Hi! Sorry for the late answer.
When I wrote this stuff, there was no 3.x version released. At that moment Blender 3.0.1 is the last version where I've tested it. At least it works for me.
I can dive in to understand what's going on, but it would take some time.

**Comment by nutti** [comment] 2022-12-02 09:57
@CheeryLee 

Thanks for your information.
But this is not a mandatory issue because I think this is an environment issue.
Actually, I could not reproduce this issue every time.
