### ISSUE TITLE
Requires updating for Blender 4.0

### ISSUE THREAD

**Issue by eason-jk** [nutti/Screencast-Keys#186] opened 2023-11-18 11:37 UTC
### System Information
  
Windows 10

Blender version: 4.0 and beyond

Does not install in Blender 4, presumably because of the python API changes.

```
  Traceback (most recent call last):
    File "D:\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 401, in enable
      mod.register()
    File "C:\Users\John Eason\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\__init__.py", line 121, in register
      utils.bl_class_registry.BlClassRegistry.register()
    File "C:\Users\John Eason\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\utils\bl_class_registry.py", line 63, in register
      bpy.utils.register_class(class_["class"])
  ValueError: bpy_struct "SK_Preferences" registration error: 'font_size' IntProperty could not register (see previous error)

```

**Comment by nutti** [comment] 2023-11-18 11:40
@eason-jk 

Actually, I could not reproduce this error.
Reinstall add-on or Blender does not work for your environment.

Also, I released Screencast Keys 3.12 today which supports Blender 4.0.
Does this work for your environment?

**Comment by eason-jk** [comment] 2023-11-18 11:42
Thank you. I've only just seen the update. I will try the new version and report back.

**Comment by eason-jk** [comment] 2023-11-18 11:51
Ok. 3.12 installs ok here but I'm getting the following error when I try to enable it:

```
Traceback (most recent call last):
  File "D:\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\John Eason\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\__init__.py", line 157, in register
    register_updater(bl_info)
  File "C:\Users\John Eason\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\__init__.py", line 103, in register_updater
    updater.init(config)
TypeError: AddonUpdaterManager.init() missing 1 required positional argument: 'config'

This is the same error that several other addons which haven't been updated are showing.

version: 4.0.0, branch: blender-v4.0-release, commit date: 2023-11-13 17:26, hash: 878f71061b8e, type: release
build date: 2023-11-14, 01:20:37
platform: 'Windows-10-10.0.19045-SP0'

Python version:
version: 3.10.13 (main, Sep 20 2023, 07:33:17) [MSC v.1928 64 bit (AMD64)]
```

**Comment by nutti** [comment] 2023-11-18 11:56
@eason-jk 

This seems curious to me. This error has already fixed in the past (#134).
Could you remove add-ons at first, then install it again?

**Comment by eason-jk** [comment] 2023-11-18 12:01
Ok. I did remove the previous 3.11 version before installing 3.12 via the Preferences > Install route and it does say "3.12" on the addon settings. I'll try again.

**Comment by eason-jk** [comment] 2023-11-18 12:04
Aha! Problem solved! - Blender required a restart before I could enable the addon.

All now working fine. Thanks for your quick response.

**Comment by nutti** [comment] 2023-11-18 12:05
Thanks.
I was glad to solve your problem.

**Closed by nutti** 2023-11-18 12:05 UTC
Labels: invalid
