### ISSUE TITLE
Internal error after switching the viewport to max area.

### ISSUE THREAD

**Issue by capnm** [nutti/Screencast-Keys#26] opened 2020-07-18 19:24 UTC
**System Information**
  
* OS: Linux
* Blender version: 2.83.2, 2.9 alpha
* Add-on version: 519e04ce95f838364f6c3fea3efe2b2419246931

**Description about the bug**  
After switching the viewport to max area [Ctrl + Space] 
the Blender terminal output is spammed (until you disable the plugin) with

```
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
internal error: modal gizmo-map handler has invalid area
...
```
Doesn't happen if the addon is deacticated. 

**Screenshots/Files** [Optional]  
![Bildschirmfoto von 2020-07-18 21-15-09](https://user-images.githubusercontent.com/4047289/87860305-9a2bbd80-c93c-11ea-8574-68fd8bad7d13.png)

**Comment by nutti** [comment] 2020-07-19 01:36
@capnm 

I could not reproduce this error.
I think this error message from Blender Internal Window System.

I found similar issue is raised in some other add-on, but I think we could not fix this from add-on level.
https://developer.blender.org/T66256

I think this does not have any serious problem judged from below comments.
https://github.com/blender/blender/blob/2d1cce8331f3ecdfb8cb0c651e111ffac5dc7153/source/blender/windowmanager/gizmo/intern/wm_gizmo_map.c#L977-L979

For now, I will close this issue due to the problem of Blender itself and the impacts to the main feature.
After this issue is fixed described in D.B.O, this error seems to be disappeared.

**Closed by nutti** 2020-07-19 01:36 UTC
Labels: wontfix

**Comment by capnm** [comment] 2020-07-19 02:11
This seems to me to be relatively serious, it begins to print the line in a tight loop (~ 100% CPU load) until I stop the add-on. I found the same issue with https://github.com/jayanam/shortcut_VUr/issues/24

**Comment by nutti** [comment] 2020-07-19 02:27
@capnm 

I understand.
But we can avoid this feature if we restart Screencast-Key or not to launch Blender from console. 
So, I said this issue is not serious.

Anyway, we could not handle this issue from add-on level as I said before.
I think the best way to solve this issue is contacting the Blender developer.
https://developer.blender.org/T66256
Or, if you can build Blender from sources, you can delete [the codes](https://github.com/blender/blender/blob/2d1cce8331f3ecdfb8cb0c651e111ffac5dc7153/source/blender/windowmanager/gizmo/intern/wm_gizmo_map.c#L977-L979) not to output these logs.

I think other add-ons which uses model operator such as https://github.com/jayanam/shortcut_VUr/issues/24 raises this issue.

**Comment by capnm** [comment] 2020-07-19 03:50
Thank you for the hints! I mentioned the issue in the upstream bug report. I've found other bad side effects as well, but I can use a screencast key tool for the operating system as a workaround, so in the end it isn't a serious problem for me ;-)

**Comment by machin3io** [comment] 2021-05-02 10:57
You can avoid this by switching the workspace back and forth. Not pretty, but at least it avoids the terminal spam:

```
current = context.workspace
other = [ws for ws in bpy.data.workspaces if ws != current]

if other:
    bpy.context.window.workspace = other[0]
    bpy.context.window.workspace = current
```
