### ISSUE TITLE
ScreenCast Keys enabled but an error report and no display of mouse or keyboard signs

### ISSUE THREAD

**Issue by anidanic** [nutti/Screencast-Keys#179] opened 2023-09-15 16:47 UTC
### System Information
  
* OS: Windows 10 Pro
* Blender version: 3.3.10
* Add-on version: 3.11

### Expected behavior

See the mouse or keyboard sign displayed in Blender as result of ScreenCast Keys

### Description about the bug**

Replication steps:
1. Install ScreenCast Keys in Blender
2. Notice ScreenCast Keys menu appears now in Blender
3. Enable the checkbox ScreenCast 
4. Enable the checkbox Experimental Get Event Aggresively
5. Go to View tab - Focal Lengt and increase e.g. from 50 mm to 55 mm.
6. Error message appears
7. Disable the checkbox ScreenCast
8. Enable the checkbox ScreenCast
9. Disable the checkbox Experimental Get Event Aggresively
10. Go to View tab - Focal Lengt and increase e.g. from 55 mm to 60 mm.
11. Error message appears, same as in step 6.
12. Press G from keyboard or other keyboard or mouse left click
13. No result displayed from ScreenCast

### Screenshots/Files [Optional]  

Screenshot for steps 6,11 with focus on error message
![image](https://github.com/nutti/Screencast-Keys/assets/57825712/0529e2bd-4ddd-4322-8af1-56d561fc7961)

Screenshot for steps 6,11
![image](https://github.com/nutti/Screencast-Keys/assets/57825712/f5d8dabb-cd43-4978-9a5d-4d8d05c0c844)

Screenshot for steps 3,4
![image](https://github.com/nutti/Screencast-Keys/assets/57825712/cbcaeef5-9d8d-43b1-89fd-8ae4ee0e7940)

Screenshot for step 5
![image](https://github.com/nutti/Screencast-Keys/assets/57825712/170c1a4b-8f3f-4b85-93fc-5b2efb83f487)

Screenshot for steps 8,9
![image](https://github.com/nutti/Screencast-Keys/assets/57825712/016c4940-d4bd-4e77-8e94-21eab90f9549)

Screenshot for step 10
![image](https://github.com/nutti/Screencast-Keys/assets/57825712/592e4a1f-3a9b-4141-8d36-4f47c985c78d)

### Additional comments [Optional]
Even if enabled, I could not make ScreenCast Keys work. This means I could not see any sign for mouse or keyboards. Regardless of how I tried, enabled, disabled, enabled. Close, Open Blender. Restart laptop. Try New file or old file etc. The scenario above was the only one that gave me an error report.

**Comment by anidanic** [comment] 2023-09-15 18:35
Found also the below in Blender Info Log:
bpy.data.window_managers["WinMan"].enable_screencast_keys = True
bpy.context.space_data.lens = 51
bpy.ops.wm.sk_screencast_keys()
Python: Traceback (most recent call last):
  File "C:\Users\anida\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1832, in modal
    regions = self.find_redraw_regions(context)
  File "C:\Users\anida\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1062, in find_redraw_regions
    rect = cls.draw_area_rect(context)
  File "C:\Users\anida\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1024, in draw_area_rect
    window, area, region, x, y = cls.get_origin(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 740, in get_origin
    draw_area_width, draw_area_height = cls.draw_area_size(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 986, in draw_area_size
    blf.size(font_id, font_size)
TypeError: blf.size() takes exactly 3 arguments (2 given)
bpy.context.space_data.lens = 52
bpy.context.space_data.lens = 52
bpy.data.window_managers["WinMan"].enable_screencast_keys = False
bpy.data.window_managers["WinMan"].enable_screencast_keys = True
bpy.context.space_data.lens = 55
bpy.ops.wm.sk_screencast_keys()
Python: Traceback (most recent call last):
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1832, in modal
    regions = self.find_redraw_regions(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1062, in find_redraw_regions
    rect = cls.draw_area_rect(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1024, in draw_area_rect
    window, area, region, x, y = cls.get_origin(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 740, in get_origin
    draw_area_width, draw_area_height = cls.draw_area_size(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 986, in draw_area_size
    blf.size(font_id, font_size)
TypeError: blf.size() takes exactly 3 arguments (2 given)
bpy.data.window_managers["WinMan"].addon_search = "scr"
bpy.data.window_managers["WinMan"].enable_screencast_keys = False
bpy.data.window_managers["WinMan"].enable_screencast_keys = True
bpy.context.space_data.lens = 60
bpy.ops.wm.sk_screencast_keys()
Python: Traceback (most recent call last):
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1832, in modal
    regions = self.find_redraw_regions(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1062, in find_redraw_regions
    rect = cls.draw_area_rect(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1024, in draw_area_rect
    window, area, region, x, y = cls.get_origin(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 740, in get_origin
    draw_area_width, draw_area_height = cls.draw_area_size(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 986, in draw_area_size
    blf.size(font_id, font_size)
TypeError: blf.size() takes exactly 3 arguments (2 given)
bpy.context.space_data.lens = 55
bpy.data.window_managers["WinMan"].enable_screencast_keys = False
bpy.data.window_managers["WinMan"].enable_screencast_keys = True
bpy.context.space_data.lens = 50
bpy.ops.wm.sk_screencast_keys()
Python: Traceback (most recent call last):
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1832, in modal
    regions = self.find_redraw_regions(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1062, in find_redraw_regions
    rect = cls.draw_area_rect(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1024, in draw_area_rect
    window, area, region, x, y = cls.get_origin(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 740, in get_origin
    draw_area_width, draw_area_height = cls.draw_area_size(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 986, in draw_area_size
    blf.size(font_id, font_size)
TypeError: blf.size() takes exactly 3 arguments (2 given)
bpy.context.space_data.lens = 55
bpy.context.space_data.lens = 60
bpy.context.space_data.lens = 50
bpy.context.space_data.lens = 55
bpy.context.space_data.lens = 50
bpy.data.window_managers["WinMan"].addon_search = ""
bpy.data.window_managers["WinMan"].addon_search = "scre"
bpy.context.space_data.system_folders_active = 1
bpy.context.space_data.system_folders_active = 1
Modules Installed (screencast_keys) from 'D:\\ForBlender\\Secret\\Add-ons\\screencast_keys.zip' into 'C:\\Users\\secret\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons'
bpy.ops.wm.sk_check_addon_update()
bpy.data.window_managers["WinMan"].enable_screencast_keys = True
bpy.context.space_data.lens = 56
bpy.ops.wm.sk_screencast_keys()
Python: Traceback (most recent call last):
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1832, in modal
    regions = self.find_redraw_regions(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1062, in find_redraw_regions
    rect = cls.draw_area_rect(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 1024, in draw_area_rect
    window, area, region, x, y = cls.get_origin(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 740, in get_origin
    draw_area_width, draw_area_height = cls.draw_area_size(context)
  File "C:\Users\secret\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\ops.py", line 986, in draw_area_size
    blf.size(font_id, font_size)
TypeError: blf.size() takes exactly 3 arguments (2 given)

**Comment by nutti** [comment] 2023-09-18 06:46
Duplicate of #177.
This issue has already fixed.

If you tried the fixed version, please install unstable version for a while.
https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md

**Closed by nutti** 2023-09-18 06:46 UTC
Labels: duplicate

**Comment by anidanic** [comment] 2023-09-18 09:38
@nutti  thank you very much for your reply! With the add-on version 3.11 it did not work, but with the unstable version, it worked fine!
