### ISSUE TITLE
unable to load addon

### ISSUE THREAD

**Issue by 3d-illusions** [nutti/Screencast-Keys#45] opened 2021-02-23 11:17 UTC
**System Information**
  
* OS: windows
* Blender version: 2.93 alpha
* Add-on version: 3.4.0

below error when trying to enable the addon in the preferences window.

Traceback (most recent call last):
  File "C:\blender\2.93\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\__init__.py", line 134, in register
    preferences.SK_Preferences.ui_in_sidebar_update_fn(prefs, context)
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\preferences.py", line 277, in ui_in_sidebar_update_fn
    bpy.utils.register_class(SK_PT_ScreencastKeys)
TypeError: validating class: Panel.bl_category expected a string type, not bpy_prop_deferred

**Comment by 3d-illusions** [comment] 2021-02-23 11:57
related to this API change?

bpy.types.Panel
Added
bpy.types.Panel.list_panel_index

**Comment by 3d-illusions** [comment] 2021-02-23 12:07
https://developer.blender.org/rB37e6a1995ac7eeabd5b6a56621ad5a850dae4149

**Comment by nutti** [comment] 2021-02-23 12:17
@3d-illusions 

Thanks for your early testing of this add-on for 2.93. I could reproduce this error.
But I don't want to support in alpha version because alpha version is not stable for add-on development.
Generally speaking, we can not predict the final specification of the API before beta version is released.

Could you redirect this issue to Blender bug tracker system or wait until when beta version is released?
I will close this issue for now. Please reopen this issue if this error still exists in beta or rc version.

**Comment by Irmitya** [comment] 2021-02-25 13:32
@3d-illusions To fix this, what you do is open the `preferences.py` file and change the variables under `SK_Preferences` to annotations.
What that means is for the words like "name = someProperty(...)", you change it to "name: someProperty(...)". 

What's happening is this addon has the code setup to register variables to be backwards compatible with 2.7x. As far as I can tell, simply changing to the proper annotations fixes without issue. 
You also have to change this for every other class if you want them to function when you go to use them. 

- - - - - -

@nutti Blender devs aren't going to revert this. It's only an issue for addons trying to do tricks/workarounds to getting their code to work with deprecated Blender versions. 
At best, if enough users across multiple addons were to complain, it could reverted for one more Blender version.

**Comment by nutti** [comment] 2021-02-26 11:50
@Irmitya 

Thanks for your following up this issue.

Yeah, your insight seems correct!
I can enable this add-on in the same environment by changing variable to annotation.
Maybe, we need to fix the compatibility code.

**Comment by nutti** [comment] 2021-02-26 12:41
I found the solution to fix this issue.
https://github.com/nutti/Screencast-Keys/archive/issue_45.zip

@3d-illusions 
Above file is now WIP status, but you may use it on your purpose.
After some cleaning up, I will merge the patch to the master branch.
Thanks for raising this issue.

**Comment by zgkony** [comment] 2021-02-26 13:38
I use this WIP for my blender v2.93,it still can Not work!
show Errors:
bpy.data.window_managers["WinMan"].addon_search = "scr"
Traceback (most recent call last):
  File "K:\3D_Software\Blender\blender-2.93.0-37e6a1995ac7-windows64\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\GZ3D\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\screencast_keys\__init__.py", line 49, in <module>
    from . import preferences
  File "C:\Users\GZ3D\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\screencast_keys\preferences.py", line 52, in <module>
    class SK_OT_UpdateAddon(bpy.types.Operator):
  File "C:\Users\GZ3D\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\screencast_keys\utils\compatibility.py", line 51, in make_annotations
    props = {k: v for k, v in cls.__dict__.items() if isinstance(v, bpy.props._PropertyDeferred)}
  File "C:\Users\GZ3D\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\screencast_keys\utils\compatibility.py", line 51, in <dictcomp>
    props = {k: v for k, v in cls.__dict__.items() if isinstance(v, bpy.props._PropertyDeferred)}
AttributeError: module 'bpy.props' has no attribute '_PropertyDeferred'

**Comment by Irmitya** [comment] 2021-02-26 13:49
@zgkony This issue is with using Blender 2.93 sometime after (Feb 04-17), when the commit from the second post here was added to the daily builds. 

Prior to that commit, the version already here works.

**Comment by nutti** [comment] 2021-02-27 00:32
I merged the patch to the master branch.
Thanks for the advice @Irmitya !

**Closed by nutti** 2021-02-27 00:32 UTC
Labels: bug
