### ISSUE TITLE
Other workspaces

### ISSUE THREAD

**Issue by Etheria** [nutti/Screencast-Keys#69] opened 2021-08-31 00:20 UTC
Screencast keys works great but only for the "Layout" workspace. I was unable to see it in any of the other screens. I especially would like to see it enabled for the Animation workspace to make tutorials for students of animation. I have tested changing the offset but it doesn't apppear
**Are you willing to contribute about this feature. (Yes/No)**  
I would help if I could but I can't.
![2021-08-31_01-12_Blender](https://user-images.githubusercontent.com/5240949/131421920-45b478da-f971-4c4e-9318-0e3b923a866b.png)

**Screenshots** [Optional]  
*It is good to understand the features if you attach the screenshotsfile.*

**Additional comments** [Optional]

**Comment by nutti** [comment] 2021-08-31 03:51
Thanks for your suggestion.

@CheeryLee 

Sorry for mentioning you here. But it may help me a lot from your knowledge.
Do you have any ideas to solve this issue?
I'm going to fix this issue by referring your previous PR.

**Comment by Etheria** [comment] 2021-08-31 08:20
Thank you for your attention. I have no knowledge of coding but I do know that screencast keys worked on all screen layouts in Blender 2.79 if that helps. Although I was told that Blender code for 2.8+ is very different.

**Comment by CheeryLee** [comment] 2021-08-31 08:20
Hmm, as far as I remember I made a small addon that works in every 3D View spaces that were opened on the screen at the same moment. But I haven't tested it with layouts. I'll take a look and provide some additional info a bit later.

**Comment by nutti** [comment] 2021-08-31 21:18
@Etheria 

Thanks for your information.
I'm not sure why Blender 2.8+ does not work, but it is a good point to inspect this issue.

@CheeryLee 

It helps me a lot. Thanks.

**Comment by CheeryLee** [comment] 2021-09-01 21:40
I didn't go deeper, but it may be helpful. There need to be `get_origin` method in `SK_OT_ScreencastKeys` class changed, more precisely what gonna be returned from it. Again, you can add your draw function via `bpy.types.SpaceView3D.draw_handler_add` to run in every `SpaceView3D`.

Look at my repo: https://github.com/CheeryLee/blender_collection_path/blob/master/show_collection_path.py
The idea is pretty simple.

**Comment by nutti** [comment] 2021-09-02 12:32
@CheeryLee 

Thanks!
From your tips, I understood the cause of the issue.
If `Origin` option is `Area` or `Region`, the displayed key and mouse will be disappeared.
But this issue can be workaround by changing `Origin` option to `Window` or `Cursor`.


@Etheria 

I think this comes from the `Origin` option.
Does your requirement achieve by changing `Origin` option to `Window` or `Cursor`?
Or, execute `Set Origin` button after changing the workplace.

**Comment by Etheria** [comment] 2021-09-02 15:05
Oh yes indeed! I'm so sorry for not noticing that button. It works fine
now. Thank you to both of you for this revelation.

**Comment by nutti** [comment] 2021-09-02 21:10
It was a good news.

I will close this issue for now. If you face with the other issues, feel free to open new one.

**Closed by nutti** 2021-09-02 21:10 UTC
Labels: invalid

**Comment by Etheria** [comment] 2021-09-03 05:57
Awesome, thanks!
