### ISSUE TITLE
Retain settings after disabling/re-enabling the addon

### ISSUE THREAD

**Issue by hced** [nutti/Screencast-Keys#55] opened 2021-05-26 15:50 UTC
I'm only using this addon occasionally, so I'd like to have it disabled when not needing it, to save space in the N-panel. When re-enabling it, my customizations are gone. It would be awesome if it could remember them, but maybe this is just how Blender works?

**Comment by nutti** [comment] 2021-05-27 11:03
@hced 

I reproduced this error.
BTW, is there any other add-ons which preserves the preference when you re-enable the add-on on the Preference?

**Comment by hced** [comment] 2021-05-27 12:33
Actually, not sure if any add-on would retain their settings after disabling them. :-) Very likely that is the case. Not on my computer atm so I can’t check.

**Comment by nutti** [comment] 2021-05-27 12:47
@hced 

Thanks.
I think remaining add-on preferences after disabling the add-on is not the best way in Blender because the official add-on does not remain the preference after disable the add-on.

>  I'd like to have it disabled when not needing it, to save space in the N-panel.

But, I think this will be solved by #56 .
So, I will close this issue for now.

**Closed by nutti** 2021-05-27 12:47 UTC
Labels: wontfix
