### ISSUE TITLE
Not working in blender 4.0

### ISSUE THREAD

**Issue by roosaramendis** [nutti/Screencast-Keys#183] opened 2023-10-21 05:11 UTC
### System Information
  
* OS: win 11
* Blender version: 4.0
* Add-on version: 3.11

### Description about the bug**

giving an error when enable addon(when click on screencast key check box in N panel ) and when starting blender. this problem only having for blender 4.0. it works fine on older versions

Python: Traceback (most recent call last):
  File "C:\Users\mendis\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\ops.py", line 1872, in modal
    # Add timer to all windows.
  File "C:\Users\mendis\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\ops.py", line 1085, in find_redraw_regions
    if intersect_aabb(region_min, region_max,
  File "C:\Users\mendis\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\ops.py", line 1047, in draw_area_rect
    ymin = region.y
  File "C:\Users\mendis\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\ops.py", line 761, in get_origin
    continue
  File "C:\Users\mendis\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\ops.py", line 1009, in draw_area_size
    draw_area_width += \
TypeError: blf.size() takes exactly 2 arguments (3 given)
 

### Screenshots/Files [Optional]  

![Screenshot 2023-10-21 103730](https://github.com/nutti/Screencast-Keys/assets/59757419/0b31999c-b468-4272-9a87-b2d59cb40e11)
![Screenshot 2023-10-21 103816](https://github.com/nutti/Screencast-Keys/assets/59757419/14e7d067-afb3-4242-a849-bd6159307863)

**Comment by nutti** [comment] 2023-10-23 08:57
Duplicate of https://github.com/nutti/Screencast-Keys/issues/177.
This issue has already fixed.

If you tried the fixed version, please install unstable version for a while.
https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md

**Closed by nutti** 2023-10-23 08:57 UTC
Labels: duplicate
