### ISSUE TITLE
Blender doesn't auto-save when Screencast keys is enabled

### ISSUE THREAD

**Issue by toshicg** [nutti/Screencast-Keys#84] opened 2021-12-13 06:01 UTC
**System Information**
Operating system: Windows-10-10.0.19042-SP0 64 Bits
Graphics card: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 472.47

** OS: Windows**
**Blender Version  3.0.0,**

**Expected behavior**  
Blender should auto-save backup files as defined in Preferences > "Save & Load" 

**Description about the bug**  
Blender doesn't auto-save when Screencast keys add-on is enabled.

**Additional comments**
Let me know if you need any additional details. 
The gist of it is:

- if screencast keys is OFF, Blender autosaves as expected
- if screencast keys is ON, Blender stops autosaving

**Comment by nutti** [comment] 2021-12-13 07:06
Thanks for reporting this.
But this is duplicate of #83

**Closed by nutti** 2021-12-13 07:06 UTC
Labels: duplicate
