### ISSUE TITLE
Blender 2.91.2 (Ubuntu) chrashes during activation

### ISSUE THREAD

**Issue by ArnoLupus** [nutti/Screencast-Keys#44] opened 2021-02-07 11:54 UTC
**System Information**
  
* OS: [Ubuntu Studio 20.10]
* Blender version: [2.91.2]
* Add-on version: [3.4]

**Expected behavior**  
*Blender stays alive*

**Description about the bug**  
*Installation of add-on works well. If you select the check box to activate the screencast-keys add-on Blender crashes  and close automatically.*

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*

**Additional comments** [Optional]

**Comment by nutti** [comment] 2021-02-07 12:13
@ArnoLupus 

I could not reproduce this error on Ubuntu.
Someone solves this issue after restarting Blender.
Could you check if the issue is gone or not after restarting Blender itself.

**Comment by ArnoLupus** [comment] 2021-02-08 22:13
Unfortunately it happens each time. Also after restarting or reinstalling of Blender 2.91.2.

**Comment by nutti** [comment] 2021-02-09 11:24
Is there any crash reports or output logs?

**Comment by nutti** [comment] 2021-02-20 08:55
I will close this for now because of no information to investigate this issue.
If there are other cases, I will check this again.

**Closed by nutti** 2021-02-20 08:55 UTC
Labels: wontfix
