### ISSUE TITLE
Using on Mac OS 12.6.1 if I Split Screens dosent show up anymore the Screencast-Keys 

### ISSUE THREAD

**Issue by HOVO3D** [nutti/Screencast-Keys#144] opened 2023-01-04 22:14 UTC
### System Information
  
* OS Mac OS 16.6.1
* Blender version: [3.7.0
* Add-on version: [e.g. 5.2]

### Expected behavior

*The behavior you expect about the feature you reported.*

### Description about the bug**

*The description about the bug.*

### Screenshots/Files [Optional]  

*It is good to solve the bug if you attach the screenshots or .blend file.*

**Comment by nutti** [comment] 2023-01-06 12:04
@HOVO3D 

Could you share the process of `Split Screens`?
I could not reproduce this issue with few information.

**Comment by HOVO3D** [comment] 2023-01-07 22:18
Hello my friend

Do you have telegram i can send you the vid that i made yesterday

Thanks best regards
________________________________
Von: nutti ***@***.***>
Gesendet: Friday, January 6, 2023 1:04:42 PM
An: nutti/Screencast-Keys ***@***.***>
Cc: Hovo 3D ***@***.***>; Mention ***@***.***>
Betreff: Re: [nutti/Screencast-Keys] Using on Mac OS 12.6.1 if I Split Screens dosent show up anymore the Screencast-Keys (Issue #144)


@HOVO3D<https://github.com/HOVO3D>

Could you share the process of Split Screens?
I could not reproduce this issue with few information.

**Comment by nutti** [comment] 2023-01-09 00:41
@HOVO3D 

Is it possible to send me the video via e-mail or link to some storage service?

**Comment by HOVO3D** [comment] 2023-01-09 08:40
Yesterday i have send it whit wetransfer bro

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: nutti ***@***.***>
Gesendet: Monday, January 9, 2023 1:41:36 AM
An: nutti/Screencast-Keys ***@***.***>
Cc: Hovo 3D ***@***.***>; Mention ***@***.***>
Betreff: Re: [nutti/Screencast-Keys] Using on Mac OS 12.6.1 if I Split Screens dosent show up anymore the Screencast-Keys (Issue #144)


@HOVO3D<https://github.com/HOVO3D>

Is it possible to send me the video via e-mail or link to some storage service?

**Comment by HOVO3D** [comment] 2023-01-09 08:49
Download-Link
https://we.tl/t-Rosta1c9dE<https://we.tl/t-Rosta1c9dE?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05>

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Hovhannes Hovhannisysan ***@***.***>
Gesendet: Monday, January 9, 2023 9:40:39 AM
An: nutti/Screencast-Keys ***@***.***>; nutti/Screencast-Keys ***@***.***>
Cc: Mention ***@***.***>
Betreff: Re: [nutti/Screencast-Keys] Using on Mac OS 12.6.1 if I Split Screens dosent show up anymore the Screencast-Keys (Issue #144)

Yesterday i have send it whit wetransfer bro

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: nutti ***@***.***>
Gesendet: Monday, January 9, 2023 1:41:36 AM
An: nutti/Screencast-Keys ***@***.***>
Cc: Hovo 3D ***@***.***>; Mention ***@***.***>
Betreff: Re: [nutti/Screencast-Keys] Using on Mac OS 12.6.1 if I Split Screens dosent show up anymore the Screencast-Keys (Issue #144)


@HOVO3D<https://github.com/HOVO3D>

Is it possible to send me the video via e-mail or link to some storage service?

**Comment by nutti** [comment] 2023-01-09 09:25
@HOVO3D 

This issue can be solved when you specify the option 'Origin' to 'Area' or 'Window'.
The value of option 'Offset' is too large to show on the split area, so the cursor will move to the outside of area.

**Comment by HOVO3D** [comment] 2023-01-09 11:00
Ok i Test it thanks bro

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: nutti ***@***.***>
Gesendet: Monday, January 9, 2023 10:25:53 AM
An: nutti/Screencast-Keys ***@***.***>
Cc: Hovo 3D ***@***.***>; Mention ***@***.***>
Betreff: Re: [nutti/Screencast-Keys] Using on Mac OS 12.6.1 if I Split Screens dosent show up anymore the Screencast-Keys (Issue #144)


@HOVO3D<https://github.com/HOVO3D>

This issue can be solved when you specify the option 'Origin' to 'Area' or 'Window'.
The value of option 'Offset' is too large to show on the split area, so the cursor will move to the outside of area.

**Comment by nutti** [comment] 2023-01-12 12:08
@HOVO3D 

Any update about this issue?
If there is no issue, I will close this issue.

**Comment by HOVO3D** [comment] 2023-01-12 12:18
Bis jetzt konnte ich es noch nicht ausprobieren ich melde mich

Besten Dank

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: nutti ***@***.***>
Gesendet: Thursday, January 12, 2023 1:08:34 PM
An: nutti/Screencast-Keys ***@***.***>
Cc: Hovo 3D ***@***.***>; Mention ***@***.***>
Betreff: Re: [nutti/Screencast-Keys] Using on Mac OS 12.6.1 if I Split Screens dosent show up anymore the Screencast-Keys (Issue #144)


@HOVO3D<https://github.com/HOVO3D>

Any update about this issue?
If there is no issue, I will close this issue.

**Comment by HOVO3D** [comment] 2023-01-12 12:19
So far I have not been able to try it out yet I will get back to you

thanks

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: nutti ***@***.***>
Gesendet: Thursday, January 12, 2023 1:08:34 PM
An: nutti/Screencast-Keys ***@***.***>
Cc: Hovo 3D ***@***.***>; Mention ***@***.***>
Betreff: Re: [nutti/Screencast-Keys] Using on Mac OS 12.6.1 if I Split Screens dosent show up anymore the Screencast-Keys (Issue #144)


@HOVO3D<https://github.com/HOVO3D>

Any update about this issue?
If there is no issue, I will close this issue.

**Comment by HOVO3D** [comment] 2023-01-13 18:01
👍all ok

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Hovhannes Hovhannisysan ***@***.***>
Gesendet: Thursday, January 12, 2023 1:19:09 PM
An: nutti/Screencast-Keys ***@***.***>; nutti/Screencast-Keys ***@***.***>
Cc: Mention ***@***.***>
Betreff: Re: [nutti/Screencast-Keys] Using on Mac OS 12.6.1 if I Split Screens dosent show up anymore the Screencast-Keys (Issue #144)

So far I have not been able to try it out yet I will get back to you

thanks

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: nutti ***@***.***>
Gesendet: Thursday, January 12, 2023 1:08:34 PM
An: nutti/Screencast-Keys ***@***.***>
Cc: Hovo 3D ***@***.***>; Mention ***@***.***>
Betreff: Re: [nutti/Screencast-Keys] Using on Mac OS 12.6.1 if I Split Screens dosent show up anymore the Screencast-Keys (Issue #144)


@HOVO3D<https://github.com/HOVO3D>

Any update about this issue?
If there is no issue, I will close this issue.

**Comment by nutti** [comment] 2023-01-14 09:18
Close this issue.

**Closed by nutti** 2023-01-14 09:18 UTC
Labels: invalid
